In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [ ]:
arr1=np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
print(arr1)
print(arr1.ndim)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
2


In [ ]:
arr2=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[33,44,55]]],)
print(arr2)
print(arr2.ndim)
arr2.shape
type(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [33 44 55]]]
3


numpy.ndarray

In [ ]:
print(arr1[1,2])

33


In [ ]:
#slicing numpy 1d array
arr5=np.array([1,2,3,4,5,6,7,8,4,3])
print(arr5[2:9])


[3 4 5 6 7 8 4]


In [ ]:
print(arr5[::2])

[1 3 5 7 4]


In [ ]:
#slicing in 2d array
arr1=np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
print(arr1[0,0:4])


[1 2 3 4]


In [ ]:
arr6=np.array([1,2,3,4])
print(arr6)
print(arr6.dtype)

[1 2 3 4]
int64


In [ ]:
#interger=i
arr6=np.array([1,2,3,4],dtype='i')
print(arr6)
print(arr6.dtype)

[1 2 3 4]
int32


In [ ]:
#string=S
arr6=np.array([1,2,3,4], dtype='S')
print(arr6)
print(arr6.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#unsigned string =U
arr6=np.array([1,2,3,4],dtype='U')
print(arr6)
print(arr6.dtype)

['1' '2' '3' '4']
<U1


In [ ]:
#float = f
arr6=np.array([1,2,3,4],dtype='f')
print(arr6)
print(arr6.dtype)

[1. 2. 3. 4.]
float32


In [ ]:
#m= timedelta
arr6=np.array([1,2,3,4], dtype='m')
print(arr6)
print(arr6.dtype)

[1 2 3 4]
timedelta64


In [ ]:
#creating 4byte array using i4
arr6=np.array([1,2,3,4], dtype='i4')
print(arr6)
print(arr6.dtype)

[1 2 3 4]
int32


In [ ]:
#joining two numpy array using concatenate
ar1=np.array([1,2,3,0,4,5])
ar2=np.array([11,11,22,33,44,55])
ar=np.concatenate((ar1,ar2))
print(ar)

[ 1  2  3  0  4  5 11 11 22 33 44 55]


In [ ]:
#along axis 0 (along row)
ar3=np.array([[1,2],[3,4]])
ar4=np.array([[5,6],[7,8]])
ar6=np.concatenate((ar3,ar4),axis=0)
print(ar6)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#along axis 1 (along column)
ar3=np.array([[1,2],[3,4]])
ar4=np.array([[5,6],[7,8]])
ar5=np.concatenate((ar3,ar4),axis=1)
print(ar5)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#splitting numpy array
arp=np.array([1,2,3,4,5,6,7,8,9,10])
new_arp=np.array_split(arp,3)
print(new_arp)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [ ]:
#ravel and flatten function help to converty any dimension array into one dimension array
ap=np.array([[[[[1,2,3,],[11,22,33],[111,222,333]]]]])
print(ap)
print(ap.ndim)

[[[[[  1   2   3]
    [ 11  22  33]
    [111 222 333]]]]]
5


In [ ]:
#ravel function
pt=ap.ravel()
print(pt)
print(pt.ndim)
print(pt[0:2])
print(pt.dtype)


[  1   2   3  11  22  33 111 222 333]
1
[1 2]
int64


In [ ]:
#flatten function
ptt=ap.flatten()
print(ptt)
print(ptt.ndim)
print(ptt[0:3])
print(ptt.dtype)

[  1   2   3  11  22  33 111 222 333]
1
[1 2 3]
int64


In [ ]:
#unique function
nn=np.array([22,3,1,34,9,2,1,33,22,6,43,5,2,34,9,1,2,3,6,43,2,3,3,4,5,4,3,77,54,34,42,55])
x=np.unique(nn, return_index=True,return_counts=True,)
print(x)

(array([ 1,  2,  3,  4,  5,  6,  9, 22, 33, 34, 42, 43, 54, 55, 77]), array([ 2,  5,  1, 23, 11,  9,  4,  0,  7,  3, 30, 10, 28, 31, 27]), array([3, 4, 5, 2, 2, 2, 2, 2, 1, 3, 1, 2, 1, 1, 1]))


In [ ]:
xp=np.unique(nn,return_inverse=True)
print(xp)

(array([ 1,  2,  3,  4,  5,  6,  9, 22, 33, 34, 42, 43, 54, 55, 77]), array([ 7,  2,  0,  9,  6,  1,  0,  8,  7,  5, 11,  4,  1,  9,  6,  0,  1,
        2,  5, 11,  1,  2,  2,  3,  4,  3,  2, 14, 12,  9, 10, 13]))


In [ ]:
#delete function
arp1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arp1)
dd=np.delete(arp1,1,axis=0)
print()
print(dd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]
